package:
  name: libskylark
  version: "0.11"

source:
  git_url: https://github.com/xdata-skylark/libskylark.git
  
requirements:
  build:
    - gcc	
    - python
    - cmake
    - git
    - boost
    - openblas
    - mpich2
    - random123
    - libelemental    
    - metis
    - fftw
    - kdt
    - combblas

  run:
    - libgcc
    - python
    - boost
    - openblas
    - mpich2
    - random123
    - libelemental
    - metis
    - fftw
    - kdt
    - combblas
    - ipython    
    - numpy
    - scipy
    - mpi4py
    - h5py
    - matplotlib
    - networkx
    - scikit-learn
    - pandas
    - sympy


about:
  home: http://xdata-skylark.github.io/libskylark
  license: Apache License, Version 2.0
  summary: 'Library for sketching-based matrix computations for Machine Learning'
