stages:
  - test
  - deploy

build_skylark:
  stage: test
  script:
    - /bin/sh script/build

deploy_docs:
  stage: deploy
  script:
    - /bin/sh script/deploy-stable
  only:
    - master

deploy_docs:
  stage: deploy
  script:
    - /bin/sh script/deploy-development
  only:
    - development
