sudo: required
dist: trusty
language: cpp

notifications:
    slack: libskylark:eZ7SJkRfpcoRYbN2Itemyn1H

cache:
  directories:
  - $HOME/.ccache

env:
  global:
    - PATH=/usr/lib/ccache/:$PATH

matrix:
  include:
  - compiler: gcc
    env:
      - MPI=/usr/include/mpich CC=gcc-4.8 CXX=g++-4.8
    addons:
      apt:
        sources:
          - sourceline: 'ppa:dzombie/ccache'
        packages:
          - ccache
          - gcc-4.8
          - g++-4.8
          - gfortran-4.8
          - libstdc++-4.8-dev
          - mpich2
          - libmpich2-dev
  #- compiler: gcc
    #env:
      #- MPI=/usr/lib/openmpi/include
    #addons:
      #apt:
        #packages:
          #- gcc-4.8
          #- g++-4.8
          #- gfortran-4.8
          #- libstdc++-4.8-dev
  #- compiler: clang
    #env:
      #- MPI=/usr/include/mpich
    #addons:
      #apt:
        #packages:
          #- clang-3.6
          #- mpich2
          #- libmpich2-dev

notifications:
  email: false

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y dpkg
  - sudo update-alternatives --set mpi $MPI
  - sudo apt-get install -qq -y libblas-dev libblas3gf liblapack-dev liblapack3gf
  - sudo apt-get install -qq -y python-dev python-setuptools libopenblas-base libopenblas-dev
  - sudo apt-get install -qq -y python-numpy python-scipy python-matplotlib
  - sudo apt-get install -qq -y libhdf5-serial-dev libfftw3-dev libfftw3-mpi-dev
  - sudo apt-get install -qq -y doxygen graphviz python-sphinx dvipng openjdk-7-jdk unzip
  - sudo pip install Cython
  - sudo easy_install mpi4py h5py numpydoc

install:
  - curl https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr
  - curl http://www.thesalmons.org/john/random123/releases/1.08/Random123-1.08.tar.gz | sudo tar -x -z --strip-components 1 -C /usr/local

script:
  - ./script/bootstrap-travis-deps
  - export ELEMENTAL_ROOT=$HOME/deps/Elemental/install
  - export BOOST_ROOT=$HOME/deps/boost_1_55_0
  - ./script/build

after_success:
  - if [ $TRAVIS_BRANCH == 'development' ]; then ./script/deploy-development; fi
  - if [ $TRAVIS_BRANCH == 'master' ]; then ./script/deploy-stable; fi
