package:
  name: libelemental
  version: "0.87.4"

source:
  git_url: https://github.com/elemental/Elemental.git

build:
  rpaths:
    - lib/
    - lib64/

requirements:
  build:
    - gcc
    - python
    - openblas
    - mpich2
    - git
    - cmake
  
  run:
    - libgcc	
    - python
    - openblas
    - mpich2
    - numpy
    - matplotlib
    - pyqt >=4,<5
    - networkx

about:
  home: http://libelemental.org
  license: New BSD license
  summary: 'C++ library for distributed memory linear algebra and optimization'
