package:
  name: libskylark-dist
  version: "0.14"

source:
  git_url: https://github.com/xdata-skylark/libskylark.git
  
requirements:
  build:
    - gcc	
    - python
    - cmake
    - git
    - boost ==1.60.0
    - openblas
    - mpich2
    - random123
    - libelemental ==0.87.4   
    - metis
    - kdt
    - combblas

  run:
    - libgcc
    - python
    - boost ==1.60.0
    - openblas
    - mpich2
    - random123
    - libelemental ==0.87.4
    - metis
    - kdt
    - combblas
    - ipython
    - jupyter    
    - numpy
    - scipy
    - mpi4py
    - h5py
    - matplotlib
    - networkx
    - scikit-learn
    - pandas
    - sympy


about:
  home: http://xdata-skylark.github.io/libskylark
  license: Apache License, Version 2.0
  summary: 'Library for sketching-based matrix computations for Machine Learning'
