package:
  name: random123
  version: "1.08"

source:
  fn: Random123-1.08.tar.gz
  url: http://www.thesalmons.org/john/random123/releases/1.08/Random123-1.08.tar.gz 
  md5: 87d2783831c7a95b244868bf754a7f50

about:
  home: http://www.thesalmons.org/john/random123
  license_file: LICENSE 
  summary: 'Library of counter-based random number generators (CBRNGs)'
